name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-12

    strategy:
      matrix:
        ios: ['15.0', '16.0']

    steps:
      - name: Check Xcode version
        run: xcodebuild -version

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test with xcodebuild
        run: xcodebuild -project my-app/my-app.xcodeproj -scheme Example -destination "platform=iOS Simulator,OS=${{ matrix.ios }},name=iPhone 13" test
