name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "iOS ${{ matrix.sdk }}"

    runs-on: macos-12

    strategy:
      matrix:
        include:
          - sdk: "14.5"
            destination: platform=iOS Simulator,OS=14.5,name=iPad (8th generation)

          - sdk: "15.0"
            destination: platform=iOS Simulator,OS=15.0,name=iPhone 8

          - sdk: "16.2"
            destination: platform=iOS Simulator,OS=16.2,name=iPhone 8

    steps:
      - name: Check Xcode version
        run: xcodebuild -version

      - name: Install xcodes
        run: brew install aria2 robotsandpencils/made/xcodes

      - name: Install iOS ${{ matrix.sdk }}
        run: sudo xcodes runtimes install "iOS ${{ matrix.sdk }}"

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test with xcodebuild
        run: xcodebuild -project my-app/my-app.xcodeproj -scheme my-appTests -destination "${{ matrix.destination }}" build test