name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: "iOS ${{ matrix.sdk }}"

    runs-on: macos-12

    strategy:
      # fail-fast: false # Don’t fail-fast so that we get all snapshot test changes
      matrix:
        include:
          - sdk: "14.5"
            destination: platform=iOS Simulator,OS=14.5,name=iPad (8th generation)

          - sdk: "15.0"
            destination: platform=iOS Simulator,OS=15.0,name=iPhone 8

          - sdk: "16.2"
            destination: platform=iOS Simulator,OS=16.2,name=iPhone 8

    steps:
    - uses: actions/checkout@v1

    - name: Prepare custom devices
      run: |
        sudo mkdir -p /Library/Developer/CoreSimulator/Profiles/Runtimes

    - name: Read env
      run: cat .github/workflows/env.properties >> $GITHUB_ENV

    - name: Switch to Xcode ${{ env.xcode_version }}
      run: sudo xcode-select -s /Applications/Xcode_${{ env.xcode_version }}.app

    - name: Install xcodes
      run: brew install aria2 xcodesorg/made/xcodes

    - name: Install iOS ${{ matrix.sdk }}
      run: sudo xcodes runtimes install "iOS ${{ matrix.sdk }}"

    - name: Build & Test
      run: xcodebuild -project my-app/my-app.xcodeproj -scheme my-appTests -destination "${{ matrix.destination }}" build test